import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:practice1/const/model/model_address.dart';
import 'package:practice1/const/model/model_program.dart';
import 'package:practice1/const/model/model_review.dart';
import 'package:practice1/const/model/model_user.dart';
import 'package:practice1/const/value/enum.dart';
import 'package:uuid/uuid.dart';

final List<String> listMainBanner = [
  'assets/image/banner1.png',
  'assets/image/banner2.png',
  'assets/image/banner3.png',
  'assets/image/banner4.png',
];

final List<String> listTitleMainBottomNavi = [
  '홈',
  '검색',
  '마이페이지',
];

final List<String> listImgSelectedMainBottomNavi = [
  'assets/icon/home_green.svg',
  'assets/icon/search_green.svg',
  'assets/icon/my_green.svg',
];

final List<String> listImgOutlinedMainBottomNavi = [
  'assets/icon/home_outline.svg',
  'assets/icon/search_outline.svg',
  'assets/icon/my_outline.svg',
];

final List<ModelReview> listSampleModelReview = [
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '1',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.recommend),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 4,
    listImgUrl: [
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
    ],
  ),
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '1',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.recommend),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '김동동 리뷰 입니다. 너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 3,
    listImgUrl: [
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      // 'assets/image/modelprogram1_image2.jpeg',
      // 'assets/image/modelprogram1_image3.jpeg',
      // 'assets/image/modelprogram1_image4.jpg',
      // 'assets/image/modelprogram1_image5.jpeg',
    ],
  ),
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '1',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.recommend),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '박둥둥 리뷰 입니다. 너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 5,
    listImgUrl: [
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      // 'assets/image/modelprogram1_image3.jpeg',
      // 'assets/image/modelprogram1_image4.jpg',
      // 'assets/image/modelprogram1_image5.jpeg',
    ],
  ),
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '2',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.hot),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '가나다 리뷰 너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 1,
    listImgUrl: [
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
  ),
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '3',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.hot),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '나다라 리뷰 입니다. 너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 1,
    listImgUrl: [
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
  ),
  ModelReview(
    uid: '1',
    dateCreate: Timestamp.now(),
    uidOfModelProgram: '4',
    modelProgram: listSampleModelProgram.firstWhere((program) => program.programType == ProgramType.hot),
    uidOfModelUser: '2',
    modelUser: ModelUser(
      uid: '2',
      dateCreate: Timestamp.now(),
      email: 'asdf@gmail.com',
      name: '김종완',
      nickname: '김종완',
      pw: '123123123',
      userImg: 'assets/image/avatar_image.png',
    ),
    listReviewKeyWord: [ReviewKeyWord.good_facility,ReviewKeyWord.good_view],
    reviewText:
        '다라마 리뷰 입니다. 너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.너무 재밌었어요 다음에 또 이용하고 싶어요.',
    starRating: 2,
    listImgUrl: [
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
  ),
];

/// 서버 연결 전에 테스트로 사용하는 프로그램 모델 리스트
final List<ModelProgram> listSampleModelProgram = [
  /// 추천 프로그램
  ModelProgram(
    uid: '1',
    dateCreate: Timestamp.now(),
    programType: ProgramType.recommend,
    listImgUrl: [
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
    ],
    name: '경복궁 한복 체험',
    desc: "아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.",
    averageStarRating: 4.5,
    countTotalReview: 1543,
    price: 10000,
    discountPercentage: 20,
    locationShortCut: "경복궁역 4번 출구에서 100m",
    listServiceType: [ServiceType.wifi, ServiceType.pet],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['한복', '경복궁'],
    modelAddress: ModelAddress(
      addressBasic: "서울 종로구 시작로 161",
      addressDetail: "경복궁 입구",
      addressPostCode: "03045",
      addressGeoPoint: GeoPoint(37.5796, 126.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌2 추천 프로그램
  ModelProgram(
    uid: '2',
    dateCreate: Timestamp.now(),
    programType: ProgramType.recommend,
    listImgUrl: [
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
    ],
    name: '시즌2 경복궁 한복 체험',
    desc: "아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.",
    averageStarRating: 4.0,
    countTotalReview: 1943,
    price: 11000,
    discountPercentage: 22,
    locationShortCut: "경복궁역 4번 출구에서 100m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['한복', '경복궁'],
    modelAddress: ModelAddress(
      addressBasic: "서울 종로구 시작로 161",
      addressDetail: "경복궁 입구",
      addressPostCode: "03045",
      addressGeoPoint: GeoPoint(37.5796, 126.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌3 추천 프로그램
  ModelProgram(
    uid: '3',
    dateCreate: Timestamp.now(),
    programType: ProgramType.recommend,
    listImgUrl: [
      'assets/image/modelprogram1_image5.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image4.jpg',
    ],
    name: '시즌3 경복궁 한복 체험',
    desc: "아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.",
    averageStarRating: 4.0,
    countTotalReview: 1943,
    price: 11000,
    discountPercentage: 22,
    locationShortCut: "경복궁역 4번 출구에서 100m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['한복', '경복궁'],
    modelAddress: ModelAddress(
      addressBasic: "서울 종로구 시작로 161",
      addressDetail: "경복궁 입구",
      addressPostCode: "03045",
      addressGeoPoint: GeoPoint(37.5796, 126.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌4 추천 프로그램
  ModelProgram(
    uid: '4',
    dateCreate: Timestamp.now(),
    programType: ProgramType.recommend,
    listImgUrl: [
      'assets/image/modelprogram1_image3.jpeg',
      'assets/image/modelprogram1_image2.jpeg',
      'assets/image/modelprogram1_image1.jpeg',
      'assets/image/modelprogram1_image4.jpg',
      'assets/image/modelprogram1_image5.jpeg',
    ],
    name: '시즌4 경복궁 한복 체험',
    desc: "아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.아름다운 한복을 입고 경복궁에서 전통 문화를 체험할 수 있어요.",
    averageStarRating: 4.0,
    countTotalReview: 1943,
    price: 11000,
    discountPercentage: 22,
    locationShortCut: "경복궁역 4번 출구에서 100m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['한복', '경복궁'],
    modelAddress: ModelAddress(
      addressBasic: "서울 종로구 시작로 161",
      addressDetail: "경복궁 입구",
      addressPostCode: "03045",
      addressGeoPoint: GeoPoint(37.5796, 126.977),
      addressRegion: "서울",
    ),
  ),

  /// 농촌 프로그램
  ModelProgram(
    uid: '5',
    dateCreate: Timestamp.now(),
    programType: ProgramType.rural,
    listImgUrl: [
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image3.png',
      'assets/image/program_card_image4.png',
    ],
    name: '농사 체험',
    desc: "농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.",
    averageStarRating: 4.4,
    countTotalReview: 1443,
    price: 9000,
    discountPercentage: 25,
    locationShortCut: "천안역 1번 출구에서 200m",
    listServiceType: [ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['농사', '농촌'],
    modelAddress: ModelAddress(
      addressBasic: "전안 천안동 111",
      addressDetail: "천안역 입구",
      addressPostCode: "12345",
      addressGeoPoint: GeoPoint(36.5796, 126.977),
      addressRegion: "천안",
    ),
  ),

  /// 시즌2 농촌 프로그램
  ModelProgram(
    uid: '6',
    dateCreate: Timestamp.now(),
    programType: ProgramType.rural,
    listImgUrl: [
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image3.png',
      'assets/image/program_card_image4.png',
    ],
    name: '시즌2 농사 체험',
    desc: "농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.",
    averageStarRating: 4.3,
    countTotalReview: 243,
    price: 9500,
    discountPercentage: 15,
    locationShortCut: "천안역 1번 출구에서 200m",
    listServiceType: [ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['농사', '농촌'],
    modelAddress: ModelAddress(
      addressBasic: "전안 천안동 111",
      addressDetail: "천안역 입구",
      addressPostCode: "12345",
      addressGeoPoint: GeoPoint(36.5796, 126.977),
      addressRegion: "천안",
    ),
  ),

  /// 시즌3 농촌 프로그램
  ModelProgram(
    uid: '7',
    dateCreate: Timestamp.now(),
    programType: ProgramType.rural,
    listImgUrl: [
      'assets/image/program_card_image3.png',
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image4.png',
    ],
    name: '시즌3 농사 체험',
    desc: "농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.",
    averageStarRating: 4.3,
    countTotalReview: 243,
    price: 9500,
    discountPercentage: 15,
    locationShortCut: "천안역 1번 출구에서 200m",
    listServiceType: [ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['농사', '농촌'],
    modelAddress: ModelAddress(
      addressBasic: "전안 천안동 111",
      addressDetail: "천안역 입구",
      addressPostCode: "12345",
      addressGeoPoint: GeoPoint(36.5796, 126.977),
      addressRegion: "천안",
    ),
  ),

  /// 시즌4 농촌 프로그램
  ModelProgram(
    uid: '8',
    dateCreate: Timestamp.now(),
    programType: ProgramType.rural,
    listImgUrl: [
      'assets/image/program_card_image4.png',
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image3.png',
    ],
    name: '시즌4 농사 체험',
    desc: "농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.농사를 직접 체험할 수 있어요. 너무 너무 즐거울 겁니다.",
    averageStarRating: 4.3,
    countTotalReview: 243,
    price: 9500,
    discountPercentage: 15,
    locationShortCut: "천안역 1번 출구에서 200m",
    listServiceType: [ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['농사', '농촌'],
    modelAddress: ModelAddress(
      addressBasic: "전안 천안동 111",
      addressDetail: "천안역 입구",
      addressPostCode: "12345",
      addressGeoPoint: GeoPoint(36.5796, 126.977),
      addressRegion: "천안",
    ),
  ),

  /// 호캉스 프로그램
  ModelProgram(
    uid: '9',
    dateCreate: Timestamp.now(),
    programType: ProgramType.staycation,
    listImgUrl: [
      'assets/image/modelprogram2_image1.jpeg',
      'assets/image/modelprogram2_image2.png',
      'assets/image/modelprogram2_image3.jpeg',
      'assets/image/modelprogram2_image4.jpeg',
      'assets/image/modelprogram2_image5.jpeg',
    ],
    name: '호캉스 체험',
    desc: "호캉스를 직접 체험할 수 있어요. 너무 즐거울 겁니다.호캉스를 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.3,
    countTotalReview: 1343,
    price: 8000,
    discountPercentage: 30,
    locationShortCut: "서울역 1번 출구에서 300m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['호캉스', '호텔'],
    modelAddress: ModelAddress(
      addressBasic: "서울 중심가 222",
      addressDetail: "서울역 1번 출구",
      addressPostCode: "23456",
      addressGeoPoint: GeoPoint(35.5796, 125.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌2 호캉스 프로그램
  ModelProgram(
    uid: '10',
    dateCreate: Timestamp.now(),
    programType: ProgramType.staycation,
    listImgUrl: [
      'assets/image/modelprogram2_image2.png',
      'assets/image/modelprogram2_image1.jpeg',
      'assets/image/modelprogram2_image3.jpeg',
      'assets/image/modelprogram2_image4.jpeg',
      'assets/image/modelprogram2_image5.jpeg',
    ],
    name: '시즌2 호캉스 체험',
    desc: "호캉스를 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.2,
    countTotalReview: 1373,
    price: 8500,
    discountPercentage: 25,
    locationShortCut: "서울역 1번 출구에서 300m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['호캉스', '호텔'],
    modelAddress: ModelAddress(
      addressBasic: "서울 중심가 222",
      addressDetail: "서울역 1번 출구",
      addressPostCode: "23456",
      addressGeoPoint: GeoPoint(35.5796, 125.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌3 호캉스 프로그램
  ModelProgram(
    uid: '11',
    dateCreate: Timestamp.now(),
    programType: ProgramType.staycation,
    listImgUrl: [
      'assets/image/modelprogram2_image3.jpeg',
      'assets/image/modelprogram2_image2.png',
      'assets/image/modelprogram2_image1.jpeg',
      'assets/image/modelprogram2_image4.jpeg',
      'assets/image/modelprogram2_image5.jpeg',
    ],
    name: '시즌3 호캉스 체험',
    desc: "호캉스를 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.2,
    countTotalReview: 1373,
    price: 8500,
    discountPercentage: 25,
    locationShortCut: "서울역 1번 출구에서 300m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['호캉스', '호텔'],
    modelAddress: ModelAddress(
      addressBasic: "서울 중심가 222",
      addressDetail: "서울역 1번 출구",
      addressPostCode: "23456",
      addressGeoPoint: GeoPoint(35.5796, 125.977),
      addressRegion: "서울",
    ),
  ),

  /// 시즌4 호캉스 프로그램
  ModelProgram(
    uid: '12',
    dateCreate: Timestamp.now(),
    programType: ProgramType.staycation,
    listImgUrl: [
      'assets/image/modelprogram2_image4.jpeg',
      'assets/image/modelprogram2_image2.png',
      'assets/image/modelprogram2_image1.jpeg',
      'assets/image/modelprogram2_image3.jpeg',
      'assets/image/modelprogram2_image5.jpeg',
    ],
    name: '시즌4 호캉스 체험',
    desc: "호캉스를 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.2,
    countTotalReview: 1373,
    price: 8500,
    discountPercentage: 25,
    locationShortCut: "서울역 1번 출구에서 300m",
    listServiceType: [ServiceType.wifi, ServiceType.pet, ServiceType.parking],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['호캉스', '호텔'],
    modelAddress: ModelAddress(
      addressBasic: "서울 중심가 222",
      addressDetail: "서울역 1번 출구",
      addressPostCode: "23456",
      addressGeoPoint: GeoPoint(35.5796, 125.977),
      addressRegion: "서울",
    ),
  ),

  /// 인기 프로그램
  ModelProgram(
    uid: '13',
    dateCreate: Timestamp.now(),
    programType: ProgramType.popular,
    listImgUrl: [
      'assets/image/program_card_image4.png',
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image3.png',
    ],
    name: '인기 많은 체험',
    desc: "인기 많은 프로그램을 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.2,
    countTotalReview: 1243,
    price: 7000,
    discountPercentage: 35,
    locationShortCut: "수원역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
      ServiceType.wifi,
      ServiceType.pet,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['인기', '유명'],
    modelAddress: ModelAddress(
      addressBasic: "수원 수원 333",
      addressDetail: "수원역 입구",
      addressPostCode: "34567",
      addressGeoPoint: GeoPoint(34.5796, 124.977),
      addressRegion: "수원",
    ),
  ),

  /// 시즌2 인기 많은 프로그램
  ModelProgram(
    uid: '14',
    dateCreate: Timestamp.now(),
    programType: ProgramType.popular,
    listImgUrl: [
      'assets/image/program_card_image1.png',
      'assets/image/program_card_image2.png',
      'assets/image/program_card_image4.png',
      'assets/image/program_card_image3.png',
    ],
    name: '시즌2 인기 많은 체험',
    desc: "인기 많은 프로그램을 직접 체험할 수 있어요. 너무 즐거울 겁니다.인기 많은 프로그램을 직접 체험할 수 있어요. 너무 즐거울 겁니다.",
    averageStarRating: 4.3,
    countTotalReview: 1283,
    price: 7500,
    discountPercentage: 30,
    locationShortCut: "수원역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['인기', '유명'],
    modelAddress: ModelAddress(
      addressBasic: "수원 수원 333",
      addressDetail: "수원역 입구",
      addressPostCode: "34567",
      addressGeoPoint: GeoPoint(34.5796, 124.977),
      addressRegion: "수원",
    ),
  ),

  /// 급상승 프로그램
  ModelProgram(
    uid: '15',
    dateCreate: Timestamp.now(),
    programType: ProgramType.hot,
    listImgUrl: [
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
    name: '급상승 프로그램',
    desc: "급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.",
    averageStarRating: 4.3,
    countTotalReview: 1283,
    price: 7500,
    discountPercentage: 30,
    locationShortCut: "안산역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['급상승', '업'],
    modelAddress: ModelAddress(
      addressBasic: "안산 안산 333",
      addressDetail: "안산역 입구",
      addressPostCode: "74567",
      addressGeoPoint: GeoPoint(34.7796, 124.177),
      addressRegion: "안산",
    ),
  ),

  /// 시즌2 급상승 프로그램
  ModelProgram(
    uid: '16',
    dateCreate: Timestamp.now(),
    programType: ProgramType.hot,
    listImgUrl: [
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
    name: '시즌2 급상승 프로그램',
    desc: "급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.",
    averageStarRating: 4.3,
    countTotalReview: 1283,
    price: 7500,
    discountPercentage: 30,
    locationShortCut: "안산역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['급상승', '업'],
    modelAddress: ModelAddress(
      addressBasic: "안산 안산 333",
      addressDetail: "안산역 입구",
      addressPostCode: "74567",
      addressGeoPoint: GeoPoint(34.7796, 124.177),
      addressRegion: "안산",
    ),
  ),

  /// 시즌3 급상승 프로그램
  ModelProgram(
    uid: '17',
    dateCreate: Timestamp.now(),
    programType: ProgramType.hot,
    listImgUrl: [
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image5.png',
    ],
    name: '시즌3 급상승 프로그램',
    desc: "급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.",
    averageStarRating: 4.3,
    countTotalReview: 1283,
    price: 7500,
    discountPercentage: 30,
    locationShortCut: "안산역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['급상승', '업'],
    modelAddress: ModelAddress(
      addressBasic: "안산 안산 333",
      addressDetail: "안산역 입구",
      addressPostCode: "74567",
      addressGeoPoint: GeoPoint(34.7796, 124.177),
      addressRegion: "안산",
    ),
  ),

  /// 시즌4 급상승 프로그램
  ModelProgram(
    uid: '18',
    dateCreate: Timestamp.now(),
    programType: ProgramType.hot,
    listImgUrl: [
      'assets/image/modelprogram3_image4.jpeg',
      'assets/image/modelprogram3_image2.png',
      'assets/image/modelprogram3_image1.png',
      'assets/image/modelprogram3_image3.png',
      'assets/image/modelprogram3_image5.png',
    ],
    name: '시즌4 급상승 프로그램',
    desc: "급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.급 상승한 프로그램을 즐겨보세요.",
    averageStarRating: 4.3,
    countTotalReview: 1283,
    price: 7500,
    discountPercentage: 30,
    locationShortCut: "안산역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['급상승', '업'],
    modelAddress: ModelAddress(
      addressBasic: "안산 안산 333",
      addressDetail: "안산역 입구",
      addressPostCode: "74567",
      addressGeoPoint: GeoPoint(34.7796, 124.177),
      addressRegion: "안산",
    ),
  ),

  /// 신규 프로그램
  ModelProgram(
    uid: '19',
    dateCreate: Timestamp.now(),
    programType: ProgramType.brand_new,
    listImgUrl: [
      'assets/image/modelprogram4_image1.jpeg',
      'assets/image/modelprogram4_image2.png',
      'assets/image/modelprogram4_image3.jpeg',
      'assets/image/modelprogram4_image4.jpeg',
      'assets/image/modelprogram4_image5.jpeg',
    ],
    name: '신규 프로그램',
    desc: "새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.",
    averageStarRating: 3.9,
    countTotalReview: 983,
    price: 5500,
    discountPercentage: 10,
    locationShortCut: "망포역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['신규', '새로운'],
    modelAddress: ModelAddress(
      addressBasic: "망포 망포 333",
      addressDetail: "망포역 입구",
      addressPostCode: "64567",
      addressGeoPoint: GeoPoint(34.7196, 124.117),
      addressRegion: "망포",
    ),
  ),

  /// 신규 프로그램
  ModelProgram(
    uid: '20',
    dateCreate: Timestamp.now(),
    programType: ProgramType.brand_new,
    listImgUrl: [
      'assets/image/modelprogram4_image2.png',
      'assets/image/modelprogram4_image1.jpeg',
      'assets/image/modelprogram4_image3.jpeg',
      'assets/image/modelprogram4_image4.jpeg',
      'assets/image/modelprogram4_image5.jpeg',
    ],
    name: '시즌2 신규 프로그램',
    desc: "새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.",
    averageStarRating: 3.9,
    countTotalReview: 983,
    price: 5500,
    discountPercentage: 10,
    locationShortCut: "망포역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['신규', '새로운'],
    modelAddress: ModelAddress(
      addressBasic: "망포 망포 333",
      addressDetail: "망포역 입구",
      addressPostCode: "64567",
      addressGeoPoint: GeoPoint(34.7196, 124.117),
      addressRegion: "망포",
    ),
  ),

  /// 시즌3 신규 프로그램
  ModelProgram(
    uid: '21',
    dateCreate: Timestamp.now(),
    programType: ProgramType.brand_new,
    listImgUrl: [
      'assets/image/modelprogram4_image3.jpeg',
      'assets/image/modelprogram4_image2.png',
      'assets/image/modelprogram4_image1.jpeg',
      'assets/image/modelprogram4_image4.jpeg',
      'assets/image/modelprogram4_image5.jpeg',
    ],
    name: '시즌3 신규 프로그램',
    desc: "새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.새로 출시된 프로그램을 즐겨보세요.",
    averageStarRating: 3.9,
    countTotalReview: 983,
    price: 5500,
    discountPercentage: 10,
    locationShortCut: "망포역 1번 출구에서 400m",
    listServiceType: [
      ServiceType.wifi,
      ServiceType.pet,
      ServiceType.parking,
    ],
    maxCountReserve: 20,
    timeProgramStart: Timestamp.now(),
    timeProgramEnd: Timestamp.now(),
    listTag: ['신규', '새로운'],
    modelAddress: ModelAddress(
      addressBasic: "망포 망포 333",
      addressDetail: "망포역 입구",
      addressPostCode: "64567",
      addressGeoPoint: GeoPoint(34.7196, 124.117),
      addressRegion: "망포",
    ),
  ),
];
